import type { Metadata } from "next";
import registerComponents from '../../../../dist/fvr-components.es'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  registerComponents();
  return (
    <html lang="en">
      <body>
        <fvr-text>Foo</fvr-text>
        {children}
      </body>
    </html>
  );
}
